[package]
name = "bee_no_std"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
winapi = { version = "^0.3.8", features = ["winuser","processthreadsapi","fileapi","processenv","winbase","shellapi","heapapi"] }


